// installer/src/pages/ProgressPage.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { invoke } from "@tauri-apps/api/core";
  import { listen } from "@tauri-apps/api/event";
  import { fade } from "svelte/transition";
  import { AlertTriangle, Loader2 } from "lucide-svelte";

  export let installPath: string;
  export let onDone: () => void;

  let percent = 0;
  let status = "Запуск установки…";
  let error: string | null = null;

  onMount(() => {
    let cancelled = false;
    const unsubs: Array<() => void> = [];

    void (async () => {
      try {
        unsubs.push(
          await listen<{ percent: number; status: string }>("install-progress", (ev) => {
            if (cancelled) return;
            percent = ev.payload.percent;
            status = ev.payload.status;
            if (ev.payload.percent >= 100) {
              setTimeout(onDone, 600);
            }
          }),
        );
        unsubs.push(
          await listen<string>("install-error", (ev) => {
            if (cancelled) return;
            error = ev.payload;
          }),
        );
        await invoke("run_install", { installPath });
      } catch (e) {
        if (!cancelled) error = String(e);
      }
    })();

    return () => {
      cancelled = true;
      unsubs.forEach((u) => u());
    };
  });
</script>

<div class="flex-1 flex flex-col items-center justify-center px-8 gap-5 text-center">
  {#if error}
    <div
      class="w-16 h-16 rounded-[var(--radius-lg)] flex items-center justify-center border"
      style:background="color-mix(in srgb, var(--danger) 14%, transparent)"
      style:border-color="color-mix(in srgb, var(--danger) 40%, transparent)"
      style:color="var(--danger)"
    >
      <AlertTriangle size={28} />
    </div>
    <div>
      <h3 class="text-[15px] font-semibold" style:color="var(--danger)">Ошибка установки</h3>
      <p class="text-[12px] mt-1.5 max-w-[420px] break-words" style:color="var(--text-secondary)">
        {error}
      </p>
    </div>
  {:else}
    <div
      class="w-16 h-16 rounded-[var(--radius-lg)] flex items-center justify-center border"
      style:background="color-mix(in srgb, var(--accent) 10%, var(--surface-1))"
      style:border-color="color-mix(in srgb, var(--accent) 35%, transparent)"
      style:color="var(--accent-light)"
    >
      <div class="animate-spin" style="animation-duration: 1.6s;">
        <Loader2 size={28} />
      </div>
    </div>

    <div in:fade={{ duration: 300 }}>
      <h2 class="text-[16px] font-semibold" style:color="var(--text)">Установка</h2>
      <p class="text-[12px] mt-1" style:color="var(--text-secondary)">Пожалуйста, подождите…</p>
    </div>

    <div class="w-full max-w-[400px] flex flex-col gap-2">
      <div
        class="relative h-2.5 rounded-full overflow-hidden border"
        style:background="color-mix(in srgb, var(--text) 6%, transparent)"
        style:border-color="var(--border)"
      >
        <div
          class="absolute inset-y-0 left-0 progress-striped transition-[width] duration-300 ease-out"
          style:width="{percent}%"
          style:background="var(--accent)"
        ></div>
      </div>
      <div class="flex items-center justify-between gap-2 text-[11px]">
        <span class="truncate" style:color="var(--text-secondary)">{status}</span>
        <span class="font-medium tabular-nums" style:color="var(--accent-light)">
          {Math.round(percent)}%
        </span>
      </div>
    </div>
  {/if}
</div>

// installer/src/pages/ProgressPage.tsx
import { useState, useEffect } from "react";
import { invoke } from "@tauri-apps/api/core";
import { listen } from "@tauri-apps/api/event";
import { motion } from "framer-motion";
import { Loader } from "lucide-react";

interface Props {
  installPath: string;
  onDone: () => void;
}

export default function ProgressPage({ installPath, onDone }: Props) {
  const [percent, setPercent] = useState(0);
  const [status, setStatus] = useState("Запуск установки...");
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;

    const setup = async () => {
      const unlistenProgress = await listen<{
        percent: number;
        status: string;
      }>("install-progress", (ev) => {
        if (cancelled) return;
        setPercent(ev.payload.percent);
        setStatus(ev.payload.status);
        if (ev.payload.percent >= 100) {
          setTimeout(onDone, 800);
        }
      });

      const unlistenError = await listen<string>("install-error", (ev) => {
        if (cancelled) return;
        setError(ev.payload);
      });

      invoke("run_install", { installPath });

      return () => {
        cancelled = true;
        unlistenProgress();
        unlistenError();
      };
    };

    let cleanup: (() => void) | undefined;
    setup().then((fn) => {
      cleanup = fn;
    });

    return () => {
      cancelled = true;
      cleanup?.();
    };
  }, [installPath, onDone]);

  return (
    <div className="flex-1 flex flex-col items-center justify-center px-10 gap-6">
      {error ? (
        <motion.div
          initial={{ scale: 0.8, opacity: 0 }}
          animate={{ scale: 1, opacity: 1 }}
          className="text-center"
        >
          <div className="w-16 h-16 rounded-2xl bg-red-500/10 border border-red-500/20 flex items-center justify-center mx-auto mb-4">
            <span className="text-2xl">✕</span>
          </div>
          <h3 className="text-lg font-semibold text-red-400">
            Ошибка установки
          </h3>
          <p className="text-sm text-white/40 mt-2 max-w-[400px] break-words">
            {error}
          </p>
        </motion.div>
      ) : (
        <>
          <motion.div
            animate={{ rotate: 360 }}
            transition={{ duration: 2, repeat: Infinity, ease: "linear" }}
          >
            <Loader size={32} className="text-jm-accent-light" />
          </motion.div>

          <div className="text-center">
            <h2 className="text-lg font-semibold text-white">Установка</h2>
            <p className="text-sm text-white/40 mt-1">
              Пожалуйста, подождите...
            </p>
          </div>

          <div className="w-full max-w-[400px]">
            <div className="relative h-3 bg-black/40 rounded-full overflow-hidden border border-white/5">
              <motion.div
                className="absolute inset-y-0 left-0 bg-gradient-to-r from-jm-accent to-jm-accent-light rounded-full progress-striped"
                initial={{ width: "0%" }}
                animate={{ width: `${percent}%` }}
                transition={{ duration: 0.3, ease: "easeOut" }}
              />
            </div>
            <div className="flex items-center justify-between mt-2">
              <span className="text-[12px] text-white/30 truncate max-w-[300px]">
                {status}
              </span>
              <span className="text-[12px] text-jm-accent-light font-medium">
                {Math.round(percent)}%
              </span>
            </div>
          </div>

          <div className="flex items-center gap-1.5 mt-2">
            {[0, 1, 2].map((i) => (
              <motion.div
                key={i}
                animate={{ opacity: [0.2, 1, 0.2], scale: [0.8, 1.1, 0.8] }}
                transition={{
                  duration: 1.2,
                  repeat: Infinity,
                  delay: i * 0.2,
                }}
                className="w-1.5 h-1.5 rounded-full bg-jm-accent/50"
              />
            ))}
          </div>
        </>
      )}
    </div>
  );
}
