// installer/src/pages/PathPage.svelte
<script lang="ts">
  import { invoke } from "@tauri-apps/api/core";
  import { open } from "@tauri-apps/plugin-dialog";
  import { fly } from "svelte/transition";
  import { quintOut } from "svelte/easing";
  import { FolderOpen, ChevronLeft, ChevronRight, HardDrive } from "lucide-svelte";

  export let installPath = "";
  export let onBack: () => void;
  export let onNext: () => void;

  type DiskInfo = { available_gb: number; required_gb: number; enough: boolean };

  let diskInfo: DiskInfo | null = null;
  let pathValid = true;

  $: {
    const p = installPath;
    void invoke<DiskInfo>("check_disk_space", { installPath: p }).then((d) => (diskInfo = d));
    void invoke<boolean>("validate_path", { path: p }).then((v) => (pathValid = v));
  }

  $: canProceed = pathValid && (diskInfo?.enough ?? true);
</script>

<div class="flex-1 flex flex-col px-7 py-5 gap-5">
  <div in:fly={{ y: -8, duration: 280, easing: quintOut, opacity: 0 }}>
    <h2 class="text-[16px] font-semibold" style:color="var(--text)">Путь установки</h2>
    <p class="text-[12px] mt-1" style:color="var(--text-secondary)">
      Выберите папку для установки лаунчера.
    </p>
  </div>

  <div
    class="flex items-center gap-2"
    in:fly={{ y: 10, duration: 300, delay: 60, easing: quintOut, opacity: 0 }}
  >
    <div class="flex-1 relative">
      <input
        type="text"
        bind:value={installPath}
        class="ui-input {pathValid ? '' : 'is-invalid'}"
      />
      {#if !pathValid}
        <span
          class="absolute right-3 top-1/2 -translate-y-1/2 text-[11px]"
          style:color="var(--danger)"
        >Недопустимый путь</span>
      {/if}
    </div>
    <button
      type="button"
      class="ui-btn ui-btn-subtle h-10 w-10 shrink-0"
      title="Выбрать папку"
      on:click={async () => {
        const selected = await open({
          directory: true,
          multiple: false,
          title: "Выберите папку для установки",
        });
        if (selected != null) {
          installPath = typeof selected === "string" ? selected : selected[0] ?? installPath;
        }
      }}
    >
      <FolderOpen size={16} />
    </button>
  </div>

  <div
    class="ui-card flex items-center gap-3 px-4 py-3"
    in:fly={{ y: 10, duration: 300, delay: 120, easing: quintOut, opacity: 0 }}
  >
    <HardDrive size={16} style="color: var(--accent)" class="shrink-0" />
    {#if diskInfo}
      <div class="flex-1 min-w-0">
        <div class="flex items-center justify-between text-[13px] gap-2">
          <span style:color="var(--text-secondary)">Свободно на диске</span>
          <span
            class="font-medium tabular-nums"
            style:color={diskInfo.enough ? "var(--accent-light)" : "var(--danger)"}
          >
            {diskInfo.available_gb.toFixed(1)} ГБ
          </span>
        </div>
        <div class="flex items-center justify-between text-[12px] mt-0.5">
          <span style:color="var(--text-secondary)">Требуется</span>
          <span class="tabular-nums" style:color="var(--text-secondary)">
            ~{Math.max(diskInfo.required_gb, 0.05).toFixed(2)} ГБ
          </span>
        </div>
      </div>
    {:else}
      <span class="text-[12px]" style:color="var(--text-secondary)">Проверка…</span>
    {/if}
  </div>

  <div class="flex-1 min-h-2"></div>

  <div
    class="flex items-center justify-between gap-3"
    in:fly={{ y: 8, duration: 280, delay: 160, easing: quintOut, opacity: 0 }}
  >
    <button type="button" on:click={onBack} class="ui-btn ui-btn-ghost">
      <ChevronLeft size={14} />
      <span>Назад</span>
    </button>
    <button
      type="button"
      disabled={!canProceed}
      on:click={onNext}
      class="ui-btn ui-btn-primary h-10 px-5"
    >
      <span>Установить</span>
      <ChevronRight size={14} />
    </button>
  </div>
</div>

// Installer/installer/src/pages/PathPage.tsx
import { useState, useEffect } from "react";
import { invoke } from "@tauri-apps/api/core";
import { open } from "@tauri-apps/plugin-dialog";
import { motion } from "framer-motion";
import { FolderOpen, ChevronLeft, ChevronRight, HardDrive } from "lucide-react";

interface Props {
  installPath: string;
  setInstallPath: (p: string) => void;
  onBack: () => void;
  onNext: () => void;
}

export default function PathPage({
  installPath,
  setInstallPath,
  onBack,
  onNext,
}: Props) {
  const [diskInfo, setDiskInfo] = useState<{
    available_gb: number;
    required_gb: number;
    enough: boolean;
  } | null>(null);
  const [pathValid, setPathValid] = useState(true);

  useEffect(() => {
    invoke<{ available_gb: number; required_gb: number; enough: boolean }>(
      "check_disk_space",
      { installPath }
    ).then(setDiskInfo);

    invoke<boolean>("validate_path", { path: installPath }).then(setPathValid);
  }, [installPath]);

  const canProceed = pathValid && (diskInfo?.enough ?? true);

  return (
    <div className="flex-1 flex flex-col px-8 py-6 gap-5">
      {/* Header */}
      <motion.div
        initial={{ y: -10, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        transition={{ duration: 0.4 }}
      >
        <h2 className="text-lg font-semibold text-white">Путь установки</h2>
        <p className="text-sm text-white/40 mt-1">
          Выберите папку для установки лаунчера
        </p>
      </motion.div>

      {/* Path input */}
      <motion.div
        initial={{ y: 10, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        transition={{ delay: 0.1, duration: 0.4 }}
        className="flex items-center gap-2"
      >
        <div className="flex-1 relative">
          <input
            type="text"
            value={installPath}
            onChange={(e) => setInstallPath(e.target.value)}
            className={`w-full px-4 py-3 bg-black/40 border rounded-xl text-sm text-white/90 
              focus:border-jm-accent/50 transition-colors ${
                pathValid ? "border-white/10" : "border-red-500/50"
              }`}
          />
          {!pathValid && (
            <span className="absolute right-3 top-1/2 -translate-y-1/2 text-[11px] text-red-400">
              Недопустимый путь
            </span>
          )}
        </div>
        <motion.button
          whileHover={{ scale: 1.05 }}
          whileTap={{ scale: 0.95 }}
          className="w-11 h-11 flex items-center justify-center rounded-xl bg-jm-accent/10 border border-jm-accent/20 hover:bg-jm-accent/20 transition-colors"
          onClick={async () => {
            const selected = await open({
              directory: true,
              multiple: false,
              title: "Выберите папку для установки",
            });
            if (selected) {
              setInstallPath(selected as string);
            }
          }}
        >
          <FolderOpen size={18} className="text-jm-accent-light" />
        </motion.button>
      </motion.div>

      {/* Disk space info */}
      <motion.div
        initial={{ y: 10, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        transition={{ delay: 0.2, duration: 0.4 }}
        className="flex items-center gap-3 px-4 py-3 bg-black/20 rounded-xl border border-white/5"
      >
        <HardDrive size={18} className="text-jm-accent/60" />
        {diskInfo ? (
          <div className="flex-1">
            <div className="flex items-center justify-between text-sm">
              <span className="text-white/50">Свободно на диске</span>
              <span
                className={`font-medium ${
                  diskInfo.enough ? "text-jm-accent-light" : "text-red-400"
                }`}
              >
                {diskInfo.available_gb.toFixed(1)} ГБ
              </span>
            </div>
            <div className="flex items-center justify-between text-[12px] mt-0.5">
              <span className="text-white/30">Требуется</span>
              <span className="text-white/40">
                ~{Math.max(diskInfo.required_gb, 0.05).toFixed(2)} ГБ
              </span>
            </div>
          </div>
        ) : (
          <span className="text-sm text-white/30">Проверка...</span>
        )}
      </motion.div>

      {/* Spacer */}
      <div className="flex-1" />

      {/* Navigation */}
      <motion.div
        initial={{ y: 10, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        transition={{ delay: 0.3, duration: 0.4 }}
        className="flex items-center justify-between"
      >
        <button
          onClick={onBack}
          className="flex items-center gap-1.5 px-4 py-2.5 text-sm text-white/50 hover:text-white/80 transition-colors rounded-lg hover:bg-white/5"
        >
          <ChevronLeft size={16} />
          Назад
        </button>
        <motion.button
          whileHover={canProceed ? { scale: 1.03 } : {}}
          whileTap={canProceed ? { scale: 0.97 } : {}}
          onClick={canProceed ? onNext : undefined}
          disabled={!canProceed}
          className={`flex items-center gap-1.5 px-6 py-2.5 rounded-xl text-sm font-semibold transition-all ${
            canProceed
              ? "bg-gradient-to-r from-jm-accent to-jm-accent-light text-jm-bg shadow-lg shadow-jm-accent/20"
              : "bg-white/5 text-white/20 cursor-not-allowed"
          }`}
        >
          Установить
          <ChevronRight size={16} />
        </motion.button>
      </motion.div>
    </div>
  );
}
